set nocompatible              " be iMproved, required
" filetype off                  " required
let mapleader = "¡"

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

call plug#begin('~/.vim/plugged')
" Plugins
" Plug 'vim-airline/vim-airline'
" Plug 'vim-airline/vim-airline-themes'
Plug 'itchyny/lightline.vim'
Plug 'airblade/vim-gitgutter'
"Plug 'ctrlpvim/ctrlp.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'Yggdroot/indentLine'
Plug 'vim-vdebug/vdebug'
Plug 'ludovicchabant/vim-gutentags'
Plug 'vim-syntastic/syntastic'
Plug 'phpactor/phpactor', {'for': 'php', 'do': 'composer install --no-dev -o'}
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'stephpy/vim-php-cs-fixer'
" Plug 'junegunn/seoul256.vim'
Plug 'morhetz/gruvbox'
Plug 'jiangmiao/auto-pairs'
" Plug 'AndrewRadev/splitjoin.vim'
" Javascript world
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'posva/vim-vue'
" Track the engine.
Plug 'SirVer/ultisnips'
" Snippets are separated from the engine. Add this if you want them:
Plug 'honza/vim-snippets'
Plug 'algotech/ultisnips-php'
Plug 'nelsyeung/twig.vim'
" Use release branch
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'chrisbra/csv.vim'
Plug 'takac/vim-hardtime'
Plug 'dense-analysis/ale'
call plug#end()

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <C-cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }

let g:ale_linter_aliases = {'vue': ['vue', 'javascript']}
let g:ale_linters = {
\ 'javascript': ['eslint'],
\ 'vue': ['eslint', 'vls'],
\ 'typescript': ['tsserver', 'tslint'],
\ 'php': [],
\}

let g:netrw_banner = 0
" let g:netrw_browse_split = 4
let g:netrw_liststyle = 4
"let g:netrw_winsize = 20

let g:gutentags_ctags_executable="ctags-u"
" let g:gutentags_ctags_extra_args=['--languague=php']

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetDirectories = ['~/.vim/plugged/vim-snippets/UltiSnips', 'UltiSnips', 'my-snippets/UltiSnips']

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on
set omnifunc=syntaxcomplete#Complete
"
set number
syntax on
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
"set cursorline
"set cursorcolumn
set ruler
" set textwidth=80
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<,space:·
set updatetime=300
" colorscheme desert
" colorscheme molokai
" set background=ligh
" set background=dark
" let g:solarized_termcolors=256
"colorscheme solarized
" colorscheme seoul256-light
" colorscheme seoul256
colorscheme gruvbox
let g:gruvbox_contrast_dark = 'soft'
set hlsearch
" set undodir=~/.vim/undodir
" set undofile
let g:loaded_matchparen = 1
let g:indentLine_setConceal = 1
set ignorecase

" Show next matched string at the center of the screen
noremap n nzz
noremap N Nzz

" turn hybrid line numbers on
"set number relativenumber
" set nu rnu

" remove trailing whitespace when saving php files
" autocmd BufWritePre *.php :%s/\s\+$//e
autocmd BufWritePre * %s/\s\+$//e

"nnoremap <C-S-j> :m .+1<CR>==
"nnoremap <C-S-k> :m .-2<CR>==
"inoremap <C-S-j> :m .+1<CR>==gi
"inoremap <C-S-k> :m .-2<CR>==gi
"vnoremap <C-S-j> :m '>+1<CR>gv=gv
"vnoremap <C-S-k> :m '<-2<CR>gv=gv
nnoremap <F4> :set number!<CR>
nnoremap <F3> :set hlsearch!<CR>
nnoremap <F2> :set list!<CR>
vnoremap . :normal .<CR>

let g:airline_disable_statusline = 1
"let g:airline#extensions#branch#enabled = 1
"let g:airline#extensions#tabline#enabled = 0
""let g:airline_theme='dark'
"let g:airline_theme='solarized'
"let g:airline_powerline_fonts = 1

"if !exists('g:airline_symbols')
    "let g:airline_symbols = {}
"endif

let g:vdebug_options= {
\    "break_on_open" : 0,
\    "watch_window_style" : 'compact',
\    "window_arrangement" : ["DebuggerWatch"]
\}

"let g:ctrlp_cmd = 'CtrlPMixed'
"let g:ctrlp_working_path_mode = 'ra'
"let g:ctrlp_max_files = 0
"let g:ctrlp_max_depth = 40
"let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
"let g:ctrlp_custom_ignore = {
    "\ 'dir':  '\v[\/]\.(git|hg|svn|node_modules|var)|(node_modules|var)$',
    "\ 'file': '\v\.(exe|so|dll)$',
"\ }

nnoremap <C-p> :Files<Cr>
nnoremap <C-g> :Rg<Cr>

command! JsonFormat :%!python -m json.tool

" Highlight a column in csv text.
" :Csv 1    " highlight first column
" :Csv 12   " highlight twelfth column
" :Csv 0    " switch off highlight
function! CSVH(colnr)
  if a:colnr > 1
    let n = a:colnr - 1
    execute 'match Keyword /^\([^,]*,\)\{'.n.'}\zs[^,]*/'
    execute 'normal! 0'.n.'f,'
  elseif a:colnr == 1
    match Keyword /^[^,]*/
    normal! 0
  else
    match
  endif
endfunction
command! -nargs=1 Csv :call CSVH(<args>)

" Syntastic
let g:syntastic_php_checkers=['php', 'phpcs', 'phpmd']
let g:syntastic_php_phpcs_args='--standard=PSR2 -n'
let g:syntastic_php_phpmd_post_args = 'cleancode,codesize,controversial,design,unusedcode'

let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_aggregate_errors = 1

" Coc mappings
" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

autocmd FileType php setlocal omnifunc=phpactor#Complete

" Import missing classes
nmap <Leader>i :call phpactor#ImportMissingClasses()<CR><CR>
" Goto definition of class or class member under the cursor
nmap <Leader>gd :call phpactor#GotoDefinition()<CR>
" Goto Implementations of interface
nmap <Leader>cf :call phpactor#CopyFile()<CR>
" Include use statement
nmap <Leader>u :call phpactor#UseAdd()<CR>
" Invoke the context menu
nmap <Leader>mm :call phpactor#ContextMenu()<CR>
" Invoke the navigation menu
nmap <Leader>nn :call phpactor#Navigate()<CR>
" Transform the classes in the current file
nmap <Leader>tt :call phpactor#Transform()<CR>
" Generate a new class (replacing the current file)
nmap <Leader>cn :call phpactor#ClassNew()<CR>
" Extract expression (normal mode)
nmap <silent><Leader>ee :call phpactor#ExtractExpression(v:false)<CR>
" Extract expression from selection
vmap <silent><Leader>ee :<C-U>call phpactor#ExtractExpression(v:true)<CR>
" Extract method from selection
vmap <silent><Leader>em :<C-U>call phpactor#ExtractMethod()<CR>

" --column: Show column number
" --line-number: Show line number
" --no-heading: Do not show file headings in results
" --fixed-strings: Search term as a literal string
" --ignore-case: Case insensitive search
" --no-ignore: Do not respect .gitignore, etc...
" --hidden: Search hidden files and folders
" --follow: Follow symlinks
" --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
" --color: Search color options
command! -bang -nargs=* Find call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --ignore-case --no-ignore --hidden --follow --glob "!.git/*" --color "always" '.shellescape(<q-args>), 1, <bang>0)
